# Use the `npm run gha:check-and-test` command to test this GitHub Action workflow locally.
name: check-and-test
on:
  # Run this workflow when a PR is 1) opened/has new commits added to it, and 2) merged into the "main" branch.
  pull_request:
    types: [opened, synchronize]
jobs:
  check-and-test:
    name: Check and test on Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run this job on both the maintenance (v18) and active (v20) Node.js LTS versions.
        # https://nodejs.org/en/about/previous-releases/#release-schedule
        node-version: [18, 20]
    steps:
      # TODO: Figure out how to move "Git checkout repository" step into .github/setup/action.yaml composite action file.
      # https://github.com/actions/checkout
      - name: Git checkout repository
        uses: actions/checkout@v4
      - name: setup
        uses: ./.github/setup/
        with:
          node-version: ${{ matrix.node-version }}
      - name: check-and-test
        uses: ./.github/check-and-test/
