# Use the `npm run ghaw:validate` command to test this GitHub Action workflow locally.
name: validate
on:
  # Run this workflow when a PR is opened and whenever it has new commits added to it.
  pull_request:
    types: [opened, synchronize]
jobs:
  validate:
    name: Validate codebase on Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run this job on both the maintenance (v18) and active (v20) Node.js LTS versions.
        # https://nodejs.org/en/about/previous-releases/#release-schedule
        node-version: [18, 20]
    steps:
      # https://github.com/actions/checkout
      - name: 🛒 Git checkout repository
        uses: actions/checkout@v4
      - name: 🔁 Run `setup` composite action
        uses: ./.github/setup/
        with:
          node-version: ${{ matrix.node-version }}
      - name: 📋 Validate codebase (🛠️ build, 🧐 check, 🧪 test)
        run: npm run validate
